task1
SpaceRanger124/react pull request #1
Opened 2020-02-20 13:00 UTC by SpaceRanger124

Task1

2020-02-21 09:56 UTC, dima19972525 commented
Карточка должна быть отдельным компонентом

2020-02-21 09:59 UTC, dima19972525 commented
сам контент приложения очень мал, расстяни его на всю страницу
![image](https://user-images.githubusercontent.com/23092460/75024070-ea941180-54a9-11ea-8aef-f32f4a2d7471.png)

2020-02-21 10:01 UTC, dima19972525 commented
и это был просто пример, как должна выглядить страница, не обязательно было использовать точно такиеже стили. Пример другого человека, проходящего курс
![image](https://user-images.githubusercontent.com/23092460/75024326-452d6d80-54aa-11ea-91e6-53e74b27c339.png)

2020-02-21 10:02 UTC, dima19972525 commented
стили моэно оставить и такие, но только расстяни плс контент

2020-02-21 10:03 UTC, dima19972525 requested changes
Поправь плс изменения выше

2020-02-21 10:09 UTC, dima19972525 commented
Вы же смотрели уроки с udemi? (если нет, то почитайте плс information страницу в курсе)

2020-02-25 11:00 UTC, SpaceRanger124 commented
Уроки с udemi просмотрел, очень информативные.
Карточку выделил в отдельный компонент.
Стили оставил прежними, но разбил по компонентам. Лишние удалил.

2020-02-25 11:12 UTC, dima19972525 approved these changes
поправь изменения выше и мерж

2020-02-25 11:12 UTC, dima19972525 commented on react-course/src/Card/Card.css
> +}
Замени стили на эти
```css
.Card {
    background-color: white;
    padding: 20px;
    font-size: calc(5px + 2vmin);
    font-weight: bold;
    color: green;
    border-style: solid;
    border-width: thick;
    margin-top: 40px;
    margin-left: 20px;
    width: 80vh;
}

.Card-text {
    margin-top: 50px;
    text-align: left;
    font-weight: normal;
    font-size: calc(3px + 2vmin);
}
```

2020-02-25 11:12 UTC, dima19972525 commented on react-course/src/Card/Card.js
> +export default card;
Замени плс на это
```js
import React from 'react';
import './Card.css';

const Card = props => {
    return (
        <div className="Card">
            <div>{props.caption}</div>
            <hr />
            <div className="Card-text">{props.description}</div>
        </div>
    );
};

export default Card;
```

2020-02-25 11:23 UTC, merged