Task6
SpaceRanger124/react pull request #6
Opened 2020-03-04 11:46 UTC by SpaceRanger124

Task6

После разбиения директорий проекта я разбил и _.css_ файлы на модули классов. В новой структуре этот стиль уже нерабочий:
```
.App-cards .Card {
    margin-top: 30px;
}
```
Поэтому я вернул старый вариант, когда _margin-top_ входил в стиль самого элемента **Card**.

2020-03-05 07:11 UTC, dima19972525 commented
Насчет margin-top. То. что margin стоит сейчас прямо компоненте может навредить. (Например, если мне нужно отрисовать компонент без этого margin)

Если есть желаени работать через модули в css, тогда предлагаю вариант: прописать css класс в файле **index.css** (например .mt-1), добавить компоненту **Card** новый пропс className, прокинуть в этот пропс '.mt-1' и передать этот пропс в руут div компонента Card,

2020-03-05 07:12 UTC, dima19972525 requested changes
поправь плс изменения ниже

2020-03-05 07:12 UTC, dima19972525 commented on react-course/src/containers/App.js
> +		],
Есть проблема (в предыдущих тасках я не трогал этот момент, но всетаки его нужно решить сейчас).
При изменении карточек, нужно менять и этот объект, т.е. когда меняется caption в самой карточке, нужно, чтобы он изменился и сдесь и т.д..
Так, как сделано сейчас, путает: при рендере карточек через массив, явно прокидываются такие пропсы как caption и description, мы передаем одни значения, но это вообще никак не влият на карточку.

2020-03-05 07:12 UTC, dima19972525 commented on react-course/src/containers/App.js
> +	    var cards = this.state.cards.slice();
используй лучше или let, или const

2020-03-05 07:12 UTC, dima19972525 commented on react-course/src/components/CardList/CardList.js
> +const cardList = (props) => props.cards.map((card, index) => {
называй функционльный компоненты также с большой буквы (нет специальной согласованности, как правильно обозначать\писать такие вещи, но я скидывал пример style guide https://github.com/airbnb/javascript/tree/master/react)

2020-03-05 07:12 UTC, dima19972525 commented on react-course/src/components/CardList/Card/Card.js
> +                    editButton={editButton}
просто перекинь в компонет CardHeader эти кнопки-иконки и поставь там условие отрисовывать их или нет

2020-03-05 07:12 UTC, dima19972525 commented on react-course/src/components/CardList/Card/Card.js
> +                    changeStyles={this.changeStyles}
changeStyles? в смысле css-styles? обзови его как-нибудь по другому (вроде onChecked)

2020-03-05 11:12 UTC, SpaceRanger124 commented
Исправил.

2020-03-06 08:37 UTC, dima19972525 commented
Покажу пример как можно сделать: добавь в cards (массив в App.js) новое свойство id (id всегда присутствует в таких структурах, так что оно полюбому должно быть в реальном мире)

Самому компоненту Card пропс id не нужен, в твоей реализации можно сделать так:

```js
updateCardHandler = cardId => (newCaption, newDescription) => {
        this.setState({
            cards: this.state.cards.map(_card => {
                if (_card.id !== cardId) {
                    return _card;
                } else {
                    return {
                        ..._card,
                        caption: newCaption,
                        description: newDescription,
                    };
                }
            }),
        });
    };
```

```js
const CardList = props =>
    props.cards.map((card, index) => {
        return (
            <Card
                className="mt-1"
                selectHandler={props.selectCardHandler}
                updateCardHandler={props.updateCardHandler(card.id)}
                caption={card.caption}
                description={card.description}
                readOnly={props.readOnly}
                key={card.caption}
            />
        );
    });
```

2020-03-06 08:39 UTC, dima19972525 requested changes
Поправь еще эти изменения (постараюсь еще проверить вечером (если успеешь сделать))

2020-03-06 08:39 UTC, dima19972525 commented on react-course/src/components/CardList/Card/Card.js
> +        description: this.props.description
Т.к. сейчас мы всегда получаем данные для caption и description из пропсов, эти 2 свойства в стейте не нужны

2020-03-06 08:39 UTC, dima19972525 commented on react-course/src/components/CardList/Card/Card.js
> +        );
`this.state.caption` привязка по свойству caption не подойдет (т.к. это свойство может быть не уникальным), если у карточек есть одинаковые заголовки, то произойдет ошибка

2020-03-06 10:26 UTC, SpaceRanger124 commented
Исправил.

2020-03-06 10:45 UTC, dima19972525 commented
Измеил заголовок, вот что созранилось в свойство
![image](https://user-images.githubusercontent.com/23092460/76076876-bf80e600-5fb0-11ea-9ea8-e5a11276f49e.png)

там должен быть простой текст

2020-03-06 10:46 UTC, dima19972525 approved these changes
пофикси изменения выше и мерж

2020-03-06 10:46 UTC, dima19972525 commented on react-course/src/components/CardList/CardList.js
> +                key={card.caption}
в качестве ключа используй id

2020-03-06 10:46 UTC, dima19972525 commented on react-course/src/containers/App.js
> +	}
тут также нужно использовать поиск по id, а не по caption

2020-03-06 11:17 UTC, SpaceRanger124 commented
Насчёт заголовка. Проверил у себя, не воспроизводится проблема:
![a1](https://user-images.githubusercontent.com/61231967/76078913-aaa65180-5fb4-11ea-9c3f-a95c732dd75f.jpg)

Надеюсь, что с изменением ключей проблема переименования заголовка исчезла, но не уверен.

2020-03-06 11:45 UTC, merged