#task8
SpaceRanger124/react pull request #8
Opened 2020-03-10 14:05 UTC by SpaceRanger124

Task8

2020-03-11 06:31 UTC, dima19972525 requested changes
Поправь плс изменения выше

2020-03-11 06:31 UTC, dima19972525 commented on react-course/src/hoc/WithLoadingDelay.js
> +export default WithLoadingDelay;
это не HOC компонент. HOC компонент - это функция, которая принимает компонент и возвращает новый компонент.
https://reactjs.org/docs/higher-order-components.html
![image](https://user-images.githubusercontent.com/23092460/76388605-8c58a100-637a-11ea-9460-19a847794fa4.png)

2020-03-11 08:51 UTC, SpaceRanger124 commented
Исправил.

2020-03-12 07:24 UTC, dima19972525 approved these changes
Насчет твоей проблемы с инпутами: поиграйся со свойствами css overflow'overflow-wrap.

Пофикси изменения и мерж

2020-03-12 07:24 UTC, dima19972525 commented on react-course/src/index.css
> +    flex: 0 0 40%;
удали это свойство

2020-03-12 07:24 UTC, dima19972525 commented on react-course/src/components/CardList/Card/Card.module.css
замени стили в этом файле на эти

```css
.Card {
    background-color: white;
    padding: 20px;
    font-size: calc(5px + 2vmin);
    font-weight: bold;
    color: green;
    border-style: solid;
    border-width: thick;
    width: 600px;
}

@media screen and (max-width: 700px) {
    .Card {
        width: 400px;
    }
}

.Card-checked {
    background-color: pink;
    padding: 20px;
    font-size: calc(5px + 2vmin);
    font-weight: bold;
    color: blue;
    font-style: italic;
    border-style: solid;
    border-width: thick;
}
```

2020-03-12 07:24 UTC, dima19972525 commented on react-course/src/hoc/WithLoadingDelay.js
> +};
замени на это

```js

const withLoadingDelay = WrappedComponent => {
    return props => {
        const [loading, setLoading] = useState(true);
        setTimeout(() => {
            setLoading(false);
        }, 2000);
        return loading ? (
            <Loader
                type="Oval"
                style={{ width: '500px', textAlign: 'center' }}
            />
        ) : (
            <WrappedComponent {...props} />
        );
    };
};

export default withLoadingDelay;
```

И переименуй сам файл с маленькой буквы

2020-03-12 07:50 UTC, merged