Task9
SpaceRanger124/react pull request #9
Opened 2020-03-12 08:02 UTC by SpaceRanger124

Task9

2020-03-13 10:07 UTC, dima19972525 commented
Добавь эти стили в Card.css (забыл проверить checked состояние)
```css
.Card {
    background-color: white;
    padding: 20px;
    font-size: calc(5px + 2vmin);
    font-weight: bold;
    color: green;
    border-style: solid;
    border-width: thick;
    width: 600px;
}

@media screen and (max-width: 700px) {
    .Card, .Card-checked {
        width: 400px;
    }
    
}

.Card-checked {
    background-color: pink;
    padding: 20px;
    font-size: calc(5px + 2vmin);
    font-weight: bold;
    color: blue;
    font-style: italic;
    border-style: solid;
    border-width: thick;
    width: 600px;

}
```

2020-03-13 10:23 UTC, dima19972525 requested changes
Самому компонету Card не нужен пропс id и не нужно связывать его с контекстом.

Ппоправь плс изменения выше

2020-03-13 10:23 UTC, dima19972525 commented on react-course/src/components/CardList/Card/Card.js
> +};
Можно добавлять isRequired свойтсво

    caption: PropTypes.string.isRequired,
Если пропс не будет передан компоненту, в консоле браузера будут ошибки

2020-03-13 10:23 UTC, dima19972525 commented on react-course/src/containers/App.js
> +
просто сразу перенеси все карточки в context и работу с ними. Для этого контекст и нужен (это как хранилище данных)

2020-03-13 10:23 UTC, dima19972525 commented on react-course/src/containers/App.js
>  				</header>
Переделай на это

```js
<header className={classes['App-header']}>
					<p>The Solar System</p>
					<div>{this.context.cards.length}</div>
				</header>
```

css

```css
.App-header div {
    position: absolute;
    display: inline-block;
    margin-left: 40%;
    border-radius: 20px;
    background: lightblue;
    color: grey;
    text-align: center;
    min-width: 30px;
    padding: 5px;
}
```

2020-03-13 10:29 UTC, SpaceRanger124 commented on react-course/src/containers/App.js
> +
Я изначально пробовал так. Но проблема в том, что если карточек нет в state, а мы меняем их содержимое, страница не обновляет их, потому что это уже не часть state и рендеринга не происходит.

2020-03-13 10:32 UTC, SpaceRanger124 commented on react-course/src/components/CardList/Card/Card.js
> +};
Компонент содержит обработку событий, которая меняет массив карточек. Без передачи айдишника в метод не узнать, какую карточку из массива нужно менять по выполнению события.

2020-03-13 10:34 UTC, dima19972525 commented on react-course/src/containers/App.js
> +
если компонент связан с контекстом и контекст изменился, то компонент должен перерендериться, можешь залить код, где ты встретил эту ошибку, я потом посмотрю

2020-03-13 12:25 UTC, SpaceRanger124 commented on react-course/src/containers/App.js
> +
Я сейчас залил изменённый код. Все карточки хранятся в контексте. Список карточек после удаления логируется. Если я выделяю карточку и удаляю её, объект из контекста удаляется (их остаётся 7 вместо 8), но сами карточки не обновляются, как и их число на экране. Если после этого сделать другое действие, вызывающее изменение состояния _App.js_, тогда компонент рендерится и изменения контекста уже применяются.

2020-03-16 07:51 UTC, dima19972525 commented
CardContext
```js
import React, { Component } from 'react';
import { v1 as uuidv1 } from 'uuid';

const CardContext = React.createContext();
const { Provider, Consumer } = CardContext;

class CardsProvider extends Component {
    state = {
        cards: [
            {
                id: uuidv1(),
                caption: 'Mercury',
                description: 'This is the first planet from the Sun.',
                isSelected: false,
            },
            {
                id: uuidv1(),
                caption: 'Venus',
                description: 'This is the second planet from the Sun.',
                isSelected: false,
            },
            {
                id: uuidv1(),
                caption: 'Earth',
                description: 'This is the third planet from the Sun.',
                isSelected: false,
            },
            {
                id: uuidv1(),
                caption: 'Mars',
                description: 'This is the fourth planet from the Sun.',
                isSelected: false,
            },
            {
                id: uuidv1(),
                caption: 'Jupiter',
                description: 'This is the fifth planet from the Sun.',
                isSelected: false,
            },
            {
                id: uuidv1(),
                caption: 'Saturn',
                description: 'This is the sixth planet from the Sun.',
                isSelected: false,
            },
            {
                id: uuidv1(),
                caption: 'Uranus',
                description: 'This is the seventh planet from the Sun.',
                isSelected: false,
            },
            {
                id: uuidv1(),
                caption: 'Neptune',
                description: 'This is the eighth planet from the Sun.',
                isSelected: false,
            },
        ],
    };

    selectCardHandler = cardId => () => {
        this.context.cards = this.context.cards.map(card => {
            if (card.id === cardId) {
                card.isSelected = !card.isSelected;
            }
            return card;
        });
    };

    updateCardHandler = cardId => (newCaption, newDescription) => {
        this.context.cards = this.context.cards.map(_card => {
            if (_card.id !== cardId) {
                return _card;
            } else {
                return {
                    ..._card,
                    caption: newCaption,
                    description: newDescription,
                };
            }
        });
    };

    render() {
        return (
            <Provider
                value={{
                    cards: this.state.cards,
                    selectCardHandler: this.selectCardHandler,
                    updateCardHandler: this.updateCardHandler,
                }}>
                {this.props.children}
            </Provider>
        );
    }
}

export { CardsProvider as Provider, Consumer, CardContext };
```

2020-03-16 07:52 UTC, dima19972525 commented
App.js (пример)
```js
import React, { Component } from 'react';
import styled from 'styled-components';
import { v1 as uuidv1 } from 'uuid';

import classes from './App.module.css';
import CardList from '../components/CardList/CardList';
import AddCardPanel from '../components/AddCardPanel/AddCardPanel';
import {
    Provider as CardsProvider,
    Consumer as CardConsumer,
} from '../context/cards-context';

class App extends Component {
    state = {
        readOnly: false,
        isAddCardPanelVisible: false,
    };

    switchReadOnly = () => {
        this.setState({
            readOnly: !this.state.readOnly,
        });
    };

    removeSelectedCards = () => {
        this.context.cards = this.context.cards.filter(
            card => !card.isSelected,
        );
        console.log(this.context.cards);
    };

    addNewCard = () => {
        this.setState({
            isAddCardPanelVisible: true,
        });
    };

    submitNewCard = (caption, description) => {
        this.context.cards = [
            ...this.context.cards,
            { id: uuidv1(), caption: caption, description: description },
        ];
        this.setState({
            isAddCardPanelVisible: false,
        });
    };

    cancelNewCard = () => {
        this.setState({
            isAddCardPanelVisible: false,
        });
    };

    render() {
        const StyledInput = styled.input`
            outline: 1px dashed purple;
            outline-offset: -1px;
            transform: scale(2);
            margin-top: 40px;
            margin-left: 30px;
        `;
        let addCardPanel = null;
        if (this.state.isAddCardPanelVisible) {
            addCardPanel = (
                <AddCardPanel
                    submit={this.submitNewCard}
                    cancel={this.cancelNewCard}
                />
            );
        }
        return (
            <CardsProvider>
                <div className={classes.App}>
                    <CardConsumer>
                        {context => (
                            <header className={classes['App-header']}>
                                <p>The Solar System</p>
                                <div>{context.cards.length}</div>
                            </header>
                        )}
                    </CardConsumer>
                    <StyledInput
                        type="checkbox"
                        id="readOnlyCheckbox"
                        checked={this.state.readOnly}
                        onChange={this.switchReadOnly}
                    />
                    <label
                        className={classes['App-checkbox-label']}
                        htmlFor="readOnlyCheckbox">
                        Read only
                    </label>
                    <div className={classes['App-button-block']}>
                        <button onClick={this.removeSelectedCards}>
                            Remove selected cards
                        </button>
                        <button onClick={this.addNewCard}>
                            Add a new card
                        </button>
                    </div>
                    {addCardPanel}
                    <div className={classes['App-cards']}>
                        <CardList readOnly={this.state.readOnly} />
                    </div>
                </div>
            </CardsProvider>
        );
    }
}

export default App;
```

2020-03-16 07:52 UTC, dima19972525 requested changes
посмотри пример и поправь изменения

2020-03-16 10:25 UTC, SpaceRanger124 commented
Методы добавления новой карточки и удаления выбранных тоже добавить в контекст?

2020-03-16 10:26 UTC, SpaceRanger124 commented
Получается, контекст будет использоваться только в App.js?

2020-03-16 10:32 UTC, dima19972525 commented
> Методы добавления новой карточки и удаления выбранных тоже добавить в контекст?

да


> Получается, контекст будет использоваться только в App.js?

1) нужно предоставить провайдер, это обертка над всем приложением (или над частью приложения которая будет иметь доступ к консюмеру)
2) консюмером оборачиваем те части, в которые хотим пробрасывать данные контекста

2020-03-16 14:13 UTC, SpaceRanger124 commented
Залил свежие изменения

2020-03-17 07:02 UTC, dima19972525 commented
при создаини новой карточки, не закрывается панель создания карточки

2020-03-17 07:04 UTC, dima19972525 approved these changes
Поправь изменения выше и мерж

2020-03-17 13:19 UTC, merged